# -*- coding: utf-8 -*-
"""Happiness.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0Tw78a_3TTULXNOFS-5Krw_-Rc4I_ey
"""

import numpy as np
import pandas as pd

df_2015 = pd.read_csv("2015.csv")
df_2016 = pd.read_csv("2016.csv")
df_2017 = pd.read_csv("2017.csv")
df_2018 = pd.read_csv("2018.csv")
df_2019 = pd.read_csv("2019.csv")
df_2020 = pd.read_csv("2020.csv")
df_2021 = pd.read_csv("2021.csv")
df_2022 = pd.read_csv("2022.csv")

df_2018 = df_2018.rename({'Country or region': 'Country'}, axis = 1)
df_2019 = df_2019.rename({'Country or region': 'Country'}, axis = 1)
df_2020 = df_2020.rename({'Country name': 'Country'}, axis = 1)
df_2021 = df_2021.rename({'Country name': 'Country'}, axis = 1)
df_2022 = df_2022.rename({'Country or region': 'Country'}, axis = 1)

df_list = [df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022]

df_top_10 = pd.DataFrame()
year = 2015
for df_year in df_list:
  df_year_new = df_year.reset_index()

  temp = df_year_new[:10][['Country']]

  temp['Year'] = year
  temp['Rank'] = df_year_new['index'] + 1
  df_top_10 = pd.concat([df_top_10, temp], axis = 0)
  year += 1

df_top_10

df_top_10 = df_top_10.replace('Luxembourg*', 'Luxembourg')

import pandas as pd
import matplotlib.pyplot as plt

def bumpchart(df, show_rank_axis= True, rank_axis_distance= 1.1, 
              ax= None, scatter= False, holes= False,
              line_args= {}, scatter_args= {}, hole_args= {}):
    
    if ax is None:
        left_yaxis= plt.gca()
    else:
        left_yaxis = ax

    # Creating the right axis.
    right_yaxis = left_yaxis.twinx()
    
    axes = [left_yaxis, right_yaxis]
    
    # Creating the far right axis if show_rank_axis is True
    if show_rank_axis:
        far_right_yaxis = left_yaxis.twinx()
        axes.append(far_right_yaxis)
    
    for col in df.columns:
        y = df[col]
        x = df.index.values
        # Plotting blank points on the right axis/axes 
        # so that they line up with the left axis.
        for axis in axes[1:]:
            axis.plot(x, y, alpha= 0)

        left_yaxis.plot(x, y, **line_args, solid_capstyle='round')
        
        # Adding scatter plots
        if scatter:
            left_yaxis.scatter(x, y, **scatter_args)
            
            #Adding see-through holes
            if holes:
                bg_color = left_yaxis.get_facecolor()
                left_yaxis.scatter(x, y, color= bg_color, **hole_args)

    # Number of lines
    lines = len(df.columns)

    y_ticks = [*range(1, lines + 1)]
    
    # Configuring the axes so that they line up well.
    for axis in axes:
        axis.invert_yaxis()
        axis.set_yticks(y_ticks)
        axis.set_ylim((lines + 0.5, 0.5))
    
    # Sorting the labels to match the ranks.
    left_labels = df.iloc[0].sort_values().index
    # right_labels = df.iloc[-1].sort_values().index
    
    left_yaxis.set_yticklabels(left_labels)
    # right_yaxis.set_yticklabels(right_labels)
    
    # Setting the position of the far right axis so that it doesn't overlap with the right axis
    if show_rank_axis:
        far_right_yaxis.spines["right"].set_position(("axes", rank_axis_distance))
    
    return axes

df_for_plot = pd.pivot_table(df_top_10, index='Year', columns='Country', values='Rank')
df_for_plot

bumpchart(df_for_plot, show_rank_axis= True, scatter= True, holes= True,
          line_args= {"linewidth": 5, "alpha": 0.5}, scatter_args= {"s": 100, "alpha": 0.8})
plt.show()

